import EuFlag from '../../assets/images/region/eu.svg';
import JpFlag from '../../assets/images/region/jp.svg';
import UsaFlag from '../../assets/images/region/us.svg';
import AsFlag from '../../assets/images/region/cn.svg';
import XxFlag from '../../assets/images/region/xx.svg';
import Windows from '../../assets/images/os/Windows.png';
import Linux from '../../assets/images/os/Linux.png';
import macOS from '../../assets/images/os/MacOS.png';
import type {Game, OS, GameRegion, GameStatus, GameOs} from '../../data/types';

const statusStyles: Record<GameStatus, string> = {
    Nothing: 'bg-status-nothing text-text-nothing',
    Boots: 'bg-status-boots',
    Menus: 'bg-status-menus',
    Ingame: 'bg-status-ingame',
    Playable: 'bg-status-playable',
};

function StatusBadge({status}: {status: GameStatus}) {
    return <span className={`rounded px-2 py-1 text-xs font-semibold ${statusStyles[status]}`}>{status}</span>;
}

function RegionBadge({region}: {region: GameRegion}) {
    switch (region) {
        case 'Europe':
            return <img src={EuFlag.src} alt="Europe Flag" className="size-8" />;
        case 'Japan':
            return <img src={JpFlag.src} alt="Japan Flag" className="size-8" />;
        case 'USA':
            return <img src={UsaFlag.src} alt="USA Flag" className="size-8" />;
        case 'Asia':
            return <img src={AsFlag.src} alt="Asia Flag" className="size-8" />;
        default:
            return <img src={XxFlag.src} alt="Unknown Flag" className="size-8" />;
    }
}

function OsBadge({os}: {os: GameOs}) {
    switch (os) {
        case 'Windows':
            return <img src={Windows.src} alt="Windows Logo" className="size-8" />;
        case 'Linux':
            return <img src={Linux.src} alt="Linux Logo" className="size-8" />;
        case 'macOS':
            return <img src={macOS.src} alt="macOS Logo" className="size-8" />;
    }
}

const startWin: OS[] = [
    {
        tag: 'Nothing',
        percent: 29.6,
        count: 185,
        total: 625,
    },
    {
        tag: 'Boots',
        percent: 19.52,
        count: 122,
        total: 625,
    },
    {
        tag: 'Menus',
        percent: 15.52,
        count: 97,
        total: 625,
    },
    {
        tag: 'Ingame',
        percent: 22.88,
        count: 143,
        total: 625,
    },
    {
        tag: 'Playable',
        percent: 12.48,
        count: 78,
        total: 625,
    },
];
const startLinux: OS[] = [
    {
        tag: 'Nothing',
        percent: 32.49,
        count: 167,
        total: 514,
    },
    {
        tag: 'Boots',
        percent: 23.74,
        count: 122,
        total: 514,
    },
    {
        tag: 'Menus',
        percent: 12.84,
        count: 66,
        total: 514,
    },
    {
        tag: 'Ingame',
        percent: 19.26,
        count: 99,
        total: 514,
    },
    {
        tag: 'Playable',
        percent: 11.67,
        count: 60,
        total: 514,
    },
];
const startMac: OS[] = [
    {
        tag: 'Nothing',
        percent: 46.6,
        count: 96,
        total: 206,
    },
    {
        tag: 'Boots',
        percent: 22.82,
        count: 47,
        total: 206,
    },
    {
        tag: 'Menus',
        percent: 14.08,
        count: 29,
        total: 206,
    },
    {
        tag: 'Ingame',
        percent: 13.11,
        count: 27,
        total: 206,
    },
    {
        tag: 'Playable',
        percent: 3.4,
        count: 7,
        total: 206,
    },
];

const SAMPLE_GAMES: Game[] = [
    {
        id: 130,
        title: 'NBA 2K18',
        code: 'CUSA08500',
        type: 'PS4game',
        status: 'Menus',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 129,
        title: 'Monster Hunter World: Iceborne',
        code: 'CUSA07713',
        type: 'PS4game',
        status: 'Boots',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 938,
        title: '2Dark',
        code: 'CUSA04802',
        type: 'PS4game',
        status: 'Playable',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 128,
        title: 'Minecraft',
        code: 'CUSA00744',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1184,
        title: 'Metaphor: ReFantazio',
        code: 'CUSA47038',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 167,
        title: 'FINAL FANTASY TYPE-0 HD',
        code: 'CUSA00994',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 178,
        title: 'RESIDENT EVIL5',
        code: 'CUSA04437',
        type: 'PS4game',
        status: 'Boots',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 234,
        title: 'Titanfall™ 2',
        code: 'CUSA04027',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1172,
        title: 'Black Clover: Quartet Knights',
        code: 'CUSA10771',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1159,
        title: 'Steel Rats',
        code: 'CUSA12994',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Japan',
        image: true,
    },
    {
        id: 180,
        title: 'Resident Evil Origins Collection',
        code: 'CUSA03178',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1050,
        title: 'Destiny 2',
        code: 'CUSA05042',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 159,
        title: 'Gravity Rush™ Remastered',
        code: 'CUSA01130',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1029,
        title: 'GRAVITY RUSH™ 2',
        code: 'CUSA03694',
        type: 'PS4game',
        status: 'Nothing',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1872,
        title: 'DARK SOULS™: REMASTERED',
        code: 'CUSA08692',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '21/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 233,
        title: "Tiny Tina's Wonderlands",
        code: 'CUSA23766',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '21/11/2025',
        region: 'Unknown',
        image: false,
    },
    {
        id: 195,
        title: 'Borderlands® 3',
        code: 'CUSA07823',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '21/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 190,
        title: 'Borderlands: The Handsome Collection',
        code: 'CUSA02893',
        type: 'PS4game',
        status: 'Nothing',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '21/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1827,
        title: 'HORROR TALES: The Wine',
        code: 'CUSA27869',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '21/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 440,
        title: 'inFAMOUS™ Second Son',
        code: 'CUSA00004',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '20/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 865,
        title: "Dragon's Crown Pro",
        code: 'CUSA10487',
        type: 'PS4game',
        status: 'Playable',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '23/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 852,
        title: 'ユニコーンオーバーロード',
        code: 'CUSA27714',
        type: 'PS4game',
        status: 'Playable',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '23/11/2025',
        region: 'Japan',
        image: true,
    },
    {
        id: 866,
        title: 'Odin Sphere Leifthrasir',
        code: 'CUSA01290',
        type: 'PS4game',
        status: 'Playable',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '23/11/2025',
        region: 'Japan',
        image: true,
    },
    {
        id: 863,
        title: '十三機兵防衛圏 プロローグ',
        code: 'CUSA14276',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '23/11/2025',
        region: 'Japan',
        image: true,
    },
    {
        id: 864,
        title: 'Clockwork Aquario',
        code: 'CUSA26908',
        type: 'PS4game',
        status: 'Playable',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '23/11/2025',
        region: 'Unknown',
        image: false,
    },
    {
        id: 2031,
        title: 'Gran Turismo®SPORT',
        code: 'CUSA03220',
        type: 'PS4game',
        status: 'Boots',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '23/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1831,
        title: 'MediEvil',
        code: 'CUSA11227',
        type: 'PS4game',
        status: 'Boots',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '23/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 135,
        title: 'PowerWash Simulator',
        code: 'CUSA29983',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 932,
        title: 'DEAD OR ALIVE 5 Last Round',
        code: 'CUSA01778',
        type: 'PS4game',
        status: 'Boots',
        os: 'Windows',
        version: '0.09.0',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 931,
        title: 'A Plague Tale: Innocence',
        code: 'CUSA10812',
        type: 'PS4game',
        status: 'Nothing',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 930,
        title: 'Potion Permit',
        code: 'CUSA33783',
        type: 'PS4game',
        status: 'Playable',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 933,
        title: 'Control',
        code: 'CUSA11454',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 134,
        title: 'Persona 5 Strikers',
        code: 'CUSA19640',
        type: 'PS4game',
        status: 'Menus',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Unknown',
        image: false,
    },
    {
        id: 133,
        title: 'Persona 5 Royal',
        code: 'CUSA17419',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 132,
        title: 'Persona 3 Reload',
        code: 'CUSA37521',
        type: 'PS4game',
        status: 'Menus',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 131,
        title: 'NEO : The World Ends with You',
        code: 'CUSA26376',
        type: 'PS4game',
        status: 'Menus',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 934,
        title: "Dead Rising 4: Frank's Big Package",
        code: 'CUSA08558',
        type: 'PS4game',
        status: 'Boots',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 937,
        title: 'Bendy and the Ink Machine',
        code: 'CUSA13635',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 936,
        title: 'DEATH STRANDING™',
        code: 'CUSA12605',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 919,
        title: 'Need for Speed™ Heat',
        code: 'CUSA15081',
        type: 'PS4game',
        status: 'Nothing',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1558,
        title: 'Hatsune Miku: VR Future Live',
        code: 'CUSA04771',
        type: 'PS4game',
        status: 'Nothing',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1557,
        title: 'Hatsune Miku: Project DIVA Future Tone',
        code: 'CUSA06093',
        type: 'PS4game',
        status: 'Playable',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1556,
        title: 'GoPro',
        code: 'CUSA04180',
        type: 'PS4game',
        status: 'Boots',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1555,
        title: 'God of War Ragnarök',
        code: 'CUSA34384',
        type: 'PS4game',
        status: 'Nothing',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1554,
        title: 'Genshin Impact',
        code: 'CUSA23681',
        type: 'PS4game',
        status: 'Boots',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1553,
        title: 'Freevee',
        code: 'CUSA25926',
        type: 'PS4game',
        status: 'Boots',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'Unknown',
        image: false,
    },
    {
        id: 1391,
        title: 'Fortnite',
        code: 'CUSA07022',
        type: 'PS4game',
        status: 'Boots',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1538,
        title: 'Fallout Shelter',
        code: 'CUSA11772',
        type: 'PS4game',
        status: 'Playable',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1537,
        title: 'Fall Guys',
        code: 'CUSA29236',
        type: 'PS4game',
        status: 'Menus',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'Unknown',
        image: false,
    },
    {
        id: 1536,
        title: 'DRIVECLUB™',
        code: 'CUSA00093',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1535,
        title: 'DOOM Eternal',
        code: 'CUSA13338',
        type: 'PS4game',
        status: 'Boots',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1534,
        title: 'DISSIDIA FINAL FANTASY NT Free Edition',
        code: 'CUSA14210',
        type: 'PS4game',
        status: 'Menus',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1533,
        title: 'Disney+',
        code: 'CUSA15607',
        type: 'PS4game',
        status: 'Boots',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1532,
        title: 'DAZN',
        code: 'CUSA09505',
        type: 'PS4game',
        status: 'Nothing',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1531,
        title: 'DanMachi BATTLE CHRONICLE',
        code: 'CUSA46310',
        type: 'PS4game',
        status: 'Boots',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1530,
        title: 'Danganronpa 1.2 RELOAD',
        code: 'CUSA06808',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1529,
        title: 'Crunchyroll',
        code: 'CUSA00095',
        type: 'PS4game',
        status: 'Nothing',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1528,
        title: 'Crow: The Legend',
        code: 'CUSA14043',
        type: 'PS4game',
        status: 'Nothing',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1526,
        title: 'CODE VEIN',
        code: 'CUSA10410',
        type: 'PS4game',
        status: 'Menus',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1525,
        title: 'Clicker Heroes',
        code: 'CUSA05209',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '25/11/2025',
        region: 'USA',
        image: true,
    },
];

export {statusStyles, SAMPLE_GAMES, type Game, StatusBadge, OsBadge, RegionBadge, startWin, startMac, startLinux, type OS};
