const compatColor = {
    Nothing: 'bg-status-nothing text-text-nothing',
    Boots: 'bg-status-boots',
    Menus: 'bg-status-menus',
    Ingame: 'bg-status-ingame',
    Playable: 'bg-status-playable',
};

const compatTextColor = {
    Nothing: 'bg-status-nothing',
    Boots: 'bg-status-boots',
    Menus: 'bg-status-menus',
    Ingame: 'bg-status-ingame',
    Playable: 'bg-status-playable',
};

const SAMPLE_GAMES = [
    {
        id: 130,
        title: 'NBA 2K18',
        code: 'CUSA08500',
        type: 'PS4game',
        status: 'Menus',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 129,
        title: 'Monster Hunter World: Iceborne',
        code: 'CUSA07713',
        type: 'PS4game',
        status: 'Boots',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 938,
        title: '2Dark',
        code: 'CUSA04802',
        type: 'PS4game',
        status: 'Playable',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 128,
        title: 'Minecraft',
        code: 'CUSA00744',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1184,
        title: 'Metaphor: ReFantazio',
        code: 'CUSA47038',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 167,
        title: 'FINAL FANTASY TYPE-0 HD',
        code: 'CUSA00994',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 178,
        title: 'RESIDENT EVIL5',
        code: 'CUSA04437',
        type: 'PS4game',
        status: 'Boots',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 234,
        title: 'Titanfall™ 2',
        code: 'CUSA04027',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1172,
        title: 'Black Clover: Quartet Knights',
        code: 'CUSA10771',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1159,
        title: 'Steel Rats',
        code: 'CUSA12994',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Japan',
        image: true,
    },
    {
        id: 180,
        title: 'Resident Evil Origins Collection',
        code: 'CUSA03178',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1050,
        title: 'Destiny 2',
        code: 'CUSA05042',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 159,
        title: 'Gravity Rush™ Remastered',
        code: 'CUSA01130',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1029,
        title: 'GRAVITY RUSH™ 2',
        code: 'CUSA03694',
        type: 'PS4game',
        status: 'Nothing',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1872,
        title: 'DARK SOULS™: REMASTERED',
        code: 'CUSA08692',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '21/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 233,
        title: "Tiny Tina's Wonderlands",
        code: 'CUSA23766',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '21/11/2025',
        region: 'Unknown',
        image: false,
    },
    {
        id: 195,
        title: 'Borderlands® 3',
        code: 'CUSA07823',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '21/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 190,
        title: 'Borderlands: The Handsome Collection',
        code: 'CUSA02893',
        type: 'PS4game',
        status: 'Nothing',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '21/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1827,
        title: 'HORROR TALES: The Wine',
        code: 'CUSA27869',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '21/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 440,
        title: 'inFAMOUS™ Second Son',
        code: 'CUSA00004',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '20/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 865,
        title: "Dragon's Crown Pro",
        code: 'CUSA10487',
        type: 'PS4game',
        status: 'Playable',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '23/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 852,
        title: 'ユニコーンオーバーロード',
        code: 'CUSA27714',
        type: 'PS4game',
        status: 'Playable',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '23/11/2025',
        region: 'Japan',
        image: true,
    },
    {
        id: 866,
        title: 'Odin Sphere Leifthrasir',
        code: 'CUSA01290',
        type: 'PS4game',
        status: 'Playable',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '23/11/2025',
        region: 'Japan',
        image: true,
    },
    {
        id: 863,
        title: '十三機兵防衛圏 プロローグ',
        code: 'CUSA14276',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '23/11/2025',
        region: 'Japan',
        image: true,
    },
    {
        id: 864,
        title: 'Clockwork Aquario',
        code: 'CUSA26908',
        type: 'PS4game',
        status: 'Playable',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '23/11/2025',
        region: 'Unknown',
        image: false,
    },
    {
        id: 2031,
        title: 'Gran Turismo®SPORT',
        code: 'CUSA03220',
        type: 'PS4game',
        status: 'Boots',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '23/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 1831,
        title: 'MediEvil',
        code: 'CUSA11227',
        type: 'PS4game',
        status: 'Boots',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '23/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 135,
        title: 'PowerWash Simulator',
        code: 'CUSA29983',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 932,
        title: 'DEAD OR ALIVE 5 Last Round',
        code: 'CUSA01778',
        type: 'PS4game',
        status: 'Boots',
        os: 'Windows',
        version: '0.09.0',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 931,
        title: 'A Plague Tale: Innocence',
        code: 'CUSA10812',
        type: 'PS4game',
        status: 'Nothing',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 930,
        title: 'Potion Permit',
        code: 'CUSA33783',
        type: 'PS4game',
        status: 'Playable',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 933,
        title: 'Control',
        code: 'CUSA11454',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 134,
        title: 'Persona 5 Strikers',
        code: 'CUSA19640',
        type: 'PS4game',
        status: 'Menus',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Unknown',
        image: false,
    },
    {
        id: 133,
        title: 'Persona 5 Royal',
        code: 'CUSA17419',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 132,
        title: 'Persona 3 Reload',
        code: 'CUSA37521',
        type: 'PS4game',
        status: 'Menus',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 131,
        title: 'NEO : The World Ends with You',
        code: 'CUSA26376',
        type: 'PS4game',
        status: 'Menus',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
    {
        id: 934,
        title: "Dead Rising 4: Frank's Big Package",
        code: 'CUSA08558',
        type: 'PS4game',
        status: 'Boots',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 937,
        title: 'Bendy and the Ink Machine',
        code: 'CUSA13635',
        type: 'PS4game',
        status: 'Ingame',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 936,
        title: 'DEATH STRANDING™',
        code: 'CUSA12605',
        type: 'PS4game',
        status: 'Menus',
        os: 'Windows',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'Europe',
        image: true,
    },
    {
        id: 919,
        title: 'Need for Speed™ Heat',
        code: 'CUSA15081',
        type: 'PS4game',
        status: 'Nothing',
        os: 'Linux',
        version: '0.12.5',
        updatedDate: '22/11/2025',
        region: 'USA',
        image: true,
    },
];

export {compatColor, SAMPLE_GAMES};
